export const CUISINE_HINTS = [
    'Afghan',
    'African',
    'American',
    'Arabian',
    'Argentine',
    'Armenian',
    'Asian',
    'Australian',
    'Austrian',
    'Bagels',
    'Bakery',
    'Bangladeshi',
    'Barbecue',
    'Belgian',
    'Brazilian',
    'British',
    'Burgers',
    'Burmese',
    'Cajun',
    'Californian',
    'Cambodian',
    'Canadian',
    'Cantonese',
    'Caribbean',
    'Catalan',
    'Chilean',
    'Chinese',
    'Colombian',
    'Comfort Food',
    'Contemporary',
    'Creole',
    'Cuban',
    'Czech',
    'Deli',
    'Dim Sum',
    'Diner',
    'Dominican',
    'Donuts',
    'Dutch',
    'Eastern European',
    'Ecuadorian',
    'Egyptian',
    'Ethiopian',
    'European',
    'Filipino',
    'Fish and Chips',
    'Fondue',
    'French',
    'Fusion',
    'Gastropub',
    'German',
    'Greek',
    'Grill',
    'Guatemalan',
    'Halal',
    'Hawaiian',
    'Healthy',
    'Himalayan',
    'Hot Dogs',
    'Hungarian',
    'Ice Cream',
    'Indian',
    'Indonesian',
    'International',
    'Irish',
    'Israeli',
    'Italian',
    'Jamaican',
    'Japanese',
    'Jewish',
    'Juice Bar',
    'Kebab',
    'Korean',
    'Kosher',
    'Laotian',
    'Latin American',
    'Lebanese',
    'Malaysian',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Modern European',
    'Mongolian',
    'Moroccan',
    'Neapolitan',
    'Nepalese',
    'New American',
    'Nicaraguan',
    'Noodles',
    'Nordic',
    'North African',
    'Organic',
    'Pakistani',
    'Pan-Asian',
    'Pasta',
    'Pastries',
    'Persian',
    'Peruvian',
    'Pizza',
    'Polish',
    'Polynesian',
    'Portuguese',
    'Pub Food',
    'Puerto Rican',
    'Ramen',
    'Raw Food',
    'Romanian',
    'Russian',
    'Salad',
    'Salvadoran',
    'Sandwiches',
    'Satay',
    'Scandinavian',
    'Scottish',
    'Seafood',
    'Sicilian',
    'Singaporean',
    'Small Plates',
    'Soul Food',
    'Soup',
    'South African',
    'South American',
    'Southern',
    'Southwestern',
    'Spanish',
    'Sri Lankan',
    'Steakhouse',
    'Street Food',
    'Sushi',
    'Swedish',
    'Swiss',
    'Szechuan',
    'Tacos',
    'Taiwanese',
    'Tapas',
    'Tartes',
    'Tea',
    'Tex-Mex',
    'Thai',
    'Tibetan',
    'Traditional',
    'Turkish',
    'Ukrainian',
    'Vegan',
    'Vegetarian',
    'Venezuelan',
    'Vietnamese',
    'Welsh',
    'Wine Bar',
    'Wings',
    'Wraps',
    'Yunnan',
    'global',
    'fusion'
  ] as const;

export const EATER_NY_URL = "https://ny.eater.com";
